In [3]:
import pandas as pd
import numpy as np

In [7]:
datas = pd.date_range("20220101", periods = 60, freq="D")

df1 = pd.DataFrame(np.random.randn(60,5), index = datas, columns = list("ABCDE"))

In [8]:
df1

                   A         B         C         D         E
2022-01-01  0.032220  1.653488  1.524655 -0.410939 -1.261822
2022-01-02 -0.185769  0.443763 -0.499169 -2.167667  0.709419
2022-01-03  0.877722 -0.549847 -0.086298 -1.101403 -0.094218
2022-01-04  0.971986 -0.113657 -1.178079 -0.432215 -0.913015
2022-01-05 -0.221100  0.876883 -0.246922 -0.088183  1.885315
2022-01-06  0.080140  0.508543  1.130949  1.622490 -0.753579
2022-01-07  0.229885  0.890652 -0.043144 -0.167281 -1.455542
2022-01-08  3.013957 -0.363184 -0.734456  1.022984  0.018469
2022-01-09 -0.323055  0.555448  0.570136  0.259144 -0.140506
2022-01-10 -0.537638  0.553633  1.415721 -0.231611 -0.346428
2022-01-11  0.284791  1.959233  1.603379  1.502010 -0.596069
2022-01-12  0.675413  0.470072  1.402715 -0.867919 -0.464085
2022-01-13 -1.208787  2.325698  0.323995  2.476061  1.096947
2022-01-14 -0.094760  1.095903 -1.462456  0.475515  0.024864
2022-01-15  0.234630  0.055771 -1.528241 -0.578428  0.994174
2022-01-16 -0.521494 -0.993061 -0.636431 -0.001968  0.127173
2022-01-17 -1.112164 -0.465483 -1.601356 -0.513643 -1.869313
2022-01-18 -1.036307 -0.520648  0.600170  0.628290  0.511573
2022-01-19  0.299527  0.909848  1.182160  1.719806 -1.006706
2022-01-20 -0.982042 -1.169289 -0.953494  0.347054  0.454813
2022-01-21  0.268729  0.697981  1.367592 -1.258107 -0.501528
2022-01-22  0.606982 -1.901220 -3.873284 -0.364914 -1.319749
2022-01-23 -1.060008  1.930005  0.446232  0.725022 -1.288616
2022-01-24  0.330082 -0.711154 -1.107422 -0.181199 -1.628411
2022-01-25  0.428814  1.885701 -1.305120 -0.120593 -0.294007
2022-01-26 -2.200477 -0.238123  1.226912 -0.868755 -0.773696
2022-01-27  0.412921  0.178647  1.848114  1.006637  0.299081
2022-01-28  0.040194 -0.549174  0.090397  2.454780 -0.309735
2022-01-29  0.194445  1.654221 -0.693616 -0.178905  0.008650
2022-01-30 -1.687525 -0.363899 -0.258655 -0.280217  1.993775
2022-01-31 -1.135526  0.214856 -0.102015 -0.297518  0.251329
2022-02-01 -0.280044 -1.444982  0.768985  1.635227  0.535259
2022-02-02  0.072011  0.473096 -0.497589 -2.288528 -1.225411
2022-02-03  0.506004 -0.222608  1.648394 -1.176744  1.157026
2022-02-04 -1.024341 -0.370941 -0.578206 -0.993444  3.120446
2022-02-05  0.263123  0.573941  0.696758  0.055764  1.574546
2022-02-06  0.291386  0.456890 -0.434980  0.720937  0.164934
2022-02-07  1.913081 -0.085058 -0.944021 -0.087858 -0.343258
2022-02-08  0.624079 -1.297543 -0.403521  1.230219 -1.691068
2022-02-09  0.522563 -0.473449 -0.746822  0.067598  0.346702
2022-02-10 -0.337454  1.068751 -1.037931  0.378791  0.728468
2022-02-11 -0.647736 -0.481719  0.123078 -0.275360 -0.307721
2022-02-12  0.556561  0.284326 -1.001073  0.766794 -0.469013
2022-02-13 -0.727135 -0.016630 -0.153964  0.859410 -2.276911
2022-02-14  0.219298 -1.339081  0.776313 -0.618706  0.080629
2022-02-15 -0.473239 -0.160510  0.314845  0.099786  1.814405
2022-02-16 -0.186876 -0.781220  2.125666  0.530892  0.476852
2022-02-17 -2.473015  0.025801 -0.154424 -0.498617  0.309217
2022-02-18 -0.948348 -0.273935  0.423541 -0.223062  0.625503
2022-02-19 -0.022222 -0.548143 -1.066828  0.653816 -0.300735
2022-02-20 -0.537039  0.210998  0.357109 -1.004207  0.885807
2022-02-21 -3.075340 -2.275128  0.652479 -0.316004 -0.521750
2022-02-22 -0.427436  0.839030  0.190195  0.918515 -1.231180
2022-02-23 -0.149643  1.423258  0.188119 -0.623009  0.108918
2022-02-24  0.228946  0.226041  0.321701  0.397593  0.954388
2022-02-25 -0.019886 -0.999037  0.323290 -0.538973 -0.025525
2022-02-26 -0.604788 -0.022102  0.366947  0.956740  1.232990
2022-02-27 -1.508000  0.995691  0.395024 -0.212480 -0.719568
2022-02-28  1.308104 -0.962153 -0.356978 -1.018043 -1.264806
2022-03-01  0.426978  0.881340 -1.504520 -1.585582  1.184420

#Vizualizar as ultimas linhas

In [10]:

df1.tail(2)

                   A         B         C         D         E
2022-02-28  1.308104 -0.962153 -0.356978 -1.018043 -1.264806
2022-03-01  0.426978  0.881340 -1.504520 -1.585582  1.184420

#Acessar o indice

In [11]:
df1.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
               '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
               '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
               '2022-01-29', '2022-01-30', '2022-01-31', '2022-02-01',
               '2022-02-02', '2022-02-03', '2022-02-04', '2022-02-05',
               '2022-02-06', '2022-02-07', '2022-02-08', '2022-02-09',
               '2022-02-10', '2022-02-11', '2022-02-12', '2022-02-13',
               '2022-02-14', '2022-02-15', '2022-02-16', '2022-02-17',
               '2022-02-18', '2022-02-19', '2022-02-20', '2022-02-21',
               '2022-02-22', '2022-02-23', '2022-02-24', '2022-02-25',
               '2022-02-26', '2022-02-27', '2022-02-28', '2022-03-01'],
              dtype='datetime64[ns]', freq='D')

#Acessar as colunas

In [12]:
df1.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [13]:
C = df1.columns

In [14]:
C

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

#Pegar somente os valores numericos

In [15]:
df1.to_numpy()

array([[ 3.22202893e-02,  1.65348758e+00,  1.52465525e+00,
        -4.10939366e-01, -1.26182242e+00],
       [-1.85769226e-01,  4.43762602e-01, -4.99168807e-01,
        -2.16766727e+00,  7.09418762e-01],
       [ 8.77722003e-01, -5.49847484e-01, -8.62977188e-02,
        -1.10140307e+00, -9.42178735e-02],
       [ 9.71985510e-01, -1.13657358e-01, -1.17807892e+00,
        -4.32214633e-01, -9.13015355e-01],
       [-2.21100207e-01,  8.76882784e-01, -2.46922451e-01,
        -8.81832873e-02,  1.88531457e+00],
       [ 8.01402872e-02,  5.08542814e-01,  1.13094941e+00,
         1.62249046e+00, -7.53579329e-01],
       [ 2.29884655e-01,  8.90651748e-01, -4.31444596e-02,
        -1.67280661e-01, -1.45554189e+00],
       [ 3.01395669e+00, -3.63183900e-01, -7.34456177e-01,
         1.02298360e+00,  1.84691336e-02],
       [-3.23055140e-01,  5.55448063e-01,  5.70135790e-01,
         2.59144303e-01, -1.40506000e-01],
       [-5.37637705e-01,  5.53632582e-01,  1.41572094e+00,
        -2.31610760e-01, -3.46428458e-01],
       [ 2.84791324e-01,  1.95923344e+00,  1.60337888e+00,
         1.50200978e+00, -5.96069493e-01],
       [ 6.75413418e-01,  4.70071636e-01,  1.40271451e+00,
        -8.67919089e-01, -4.64084708e-01],
       [-1.20878729e+00,  2.32569750e+00,  3.23994907e-01,
         2.47606125e+00,  1.09694738e+00],
       [-9.47598956e-02,  1.09590263e+00, -1.46245632e+00,
         4.75515028e-01,  2.48640693e-02],
       [ 2.34629718e-01,  5.57705317e-02, -1.52824099e+00,
        -5.78428292e-01,  9.94174102e-01],
       [-5.21493941e-01, -9.93061388e-01, -6.36431273e-01,
        -1.96849477e-03,  1.27173203e-01],
       [-1.11216378e+00, -4.65482968e-01, -1.60135558e+00,
        -5.13642513e-01, -1.86931349e+00],
       [-1.03630713e+00, -5.20648358e-01,  6.00169527e-01,
         6.28290471e-01,  5.11572917e-01],
       [ 2.99526737e-01,  9.09848489e-01,  1.18216002e+00,
         1.71980607e+00, -1.00670650e+00],
       [-9.82042142e-01, -1.16928949e+00, -9.53493950e-01,
         3.47054163e-01,  4.54813476e-01],
       [ 2.68729039e-01,  6.97980642e-01,  1.36759247e+00,
        -1.25810691e+00, -5.01528366e-01],
       [ 6.06981837e-01, -1.90122048e+00, -3.87328376e+00,
        -3.64913718e-01, -1.31974877e+00],
       [-1.06000750e+00,  1.93000471e+00,  4.46232188e-01,
         7.25021669e-01, -1.28861642e+00],
       [ 3.30082456e-01, -7.11154009e-01, -1.10742237e+00,
        -1.81198619e-01, -1.62841061e+00],
       [ 4.28814330e-01,  1.88570125e+00, -1.30511981e+00,
        -1.20592525e-01, -2.94006833e-01],
       [-2.20047684e+00, -2.38123408e-01,  1.22691247e+00,
        -8.68754712e-01, -7.73696232e-01],
       [ 4.12920769e-01,  1.78646747e-01,  1.84811412e+00,
         1.00663723e+00,  2.99080547e-01],
       [ 4.01936317e-02, -5.49173684e-01,  9.03973584e-02,
         2.45477968e+00, -3.09734927e-01],
       [ 1.94445133e-01,  1.65422093e+00, -6.93616455e-01,
        -1.78904604e-01,  8.64979718e-03],
       [-1.68752491e+00, -3.63899332e-01, -2.58654803e-01,
        -2.80217128e-01,  1.99377523e+00],
       [-1.13552580e+00,  2.14855800e-01, -1.02014563e-01,
        -2.97517885e-01,  2.51329070e-01],
       [-2.80043683e-01, -1.44498203e+00,  7.68984841e-01,
         1.63522749e+00,  5.35259293e-01],
       [ 7.20105772e-02,  4.73096261e-01, -4.97588566e-01,
        -2.28852769e+00, -1.22541145e+00],
       [ 5.06003970e-01, -2.22607817e-01,  1.64839441e+00,
        -1.17674424e+00,  1.15702611e+00],
       [-1.02434094e+00, -3.70941174e-01, -5.78206175e-01,
        -9.93443671e-01,  3.12044596e+00],
       [ 2.63122533e-01,  5.73940975e-01,  6.96758154e-01,
         5.57641316e-02,  1.57454586e+00],
       [ 2.91385903e-01,  4.56890329e-01, -4.34979604e-01,
         7.20936921e-01,  1.64934256e-01],
       [ 1.91308097e+00, -8.50581234e-02, -9.44021123e-01,
        -8.78582297e-02, -3.43257791e-01],
       [ 6.24078909e-01, -1.29754335e+00, -4.03521219e-01,
         1.23021916e+00, -1.69106825e+00],
       [ 5.22563012e-01, -4.73449400e-01, -7.46822464e-01,
         6.75976806e-02,  3.46701792e-01],
       [-3.37453749e-01,  1.06875069e+00, -1.03793066e+00,
         3.78790997e-01,  7.28468044e-01],
       [-6.47736220e-01, -4.81718678e-01,  1.23078379e-01,
        -2.75360455e-01, -3.07721038e-01],
       [ 5.56561444e-01,  2.84325907e-01, -1.00107291e+00,
         7.66793782e-01, -4.69012817e-01],
       [-7.27135128e-01, -1.66304423e-02, -1.53964451e-01,
         8.59409506e-01, -2.27691119e+00],
       [ 2.19297670e-01, -1.33908128e+00,  7.76313436e-01,
        -6.18705722e-01,  8.06285388e-02],
       [-4.73238516e-01, -1.60509706e-01,  3.14845101e-01,
         9.97855544e-02,  1.81440503e+00],
       [-1.86876159e-01, -7.81219979e-01,  2.12566588e+00,
         5.30891570e-01,  4.76851697e-01],
       [-2.47301506e+00,  2.58009843e-02, -1.54424359e-01,
        -4.98617196e-01,  3.09217103e-01],
       [-9.48347638e-01, -2.73935054e-01,  4.23541470e-01,
        -2.23061754e-01,  6.25503382e-01],
       [-2.22221474e-02, -5.48143383e-01, -1.06682806e+00,
         6.53816366e-01, -3.00734751e-01],
       [-5.37039106e-01,  2.10997615e-01,  3.57108778e-01,
        -1.00420722e+00,  8.85806688e-01],
       [-3.07533973e+00, -2.27512785e+00,  6.52478841e-01,
        -3.16003616e-01, -5.21749954e-01],
       [-4.27436498e-01,  8.39030452e-01,  1.90195276e-01,
         9.18515149e-01, -1.23118048e+00],
       [-1.49643045e-01,  1.42325769e+00,  1.88119218e-01,
        -6.23008970e-01,  1.08917790e-01],
       [ 2.28946294e-01,  2.26041469e-01,  3.21700520e-01,
         3.97593326e-01,  9.54388295e-01],
       [-1.98860523e-02, -9.99037418e-01,  3.23289893e-01,
        -5.38973075e-01, -2.55251591e-02],
       [-6.04788425e-01, -2.21020436e-02,  3.66947131e-01,
         9.56739657e-01,  1.23298961e+00],
       [-1.50800007e+00,  9.95691377e-01,  3.95023888e-01,
        -2.12479643e-01, -7.19567735e-01],
       [ 1.30810393e+00, -9.62153153e-01, -3.56977947e-01,
        -1.01804293e+00, -1.26480590e+00],
       [ 4.26978050e-01,  8.81339649e-01, -1.50452031e+00,
        -1.58558164e+00,  1.18441999e+00]])

Transpoe colunas em em Linhas

#Obter a Transposta de um Conjunto de Dados

In [16]:
df1.T

,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10,...,2022-02-20,2022-02-21,2022-02-22,2022-02-23,2022-02-24,2022-02-25,2022-02-26,2022-02-27,2022-02-28,2022-03-01
A,0.032220,-0.185769,0.877722,0.971986,-0.221100,0.080140,0.229885,3.013957,-0.323055,-0.537638,...,-0.537039,-3.075340,-0.427436,-0.149643,0.228946,-0.019886,-0.604788,-1.508000,1.308104,0.426978
B,1.653488,0.443763,-0.549847,-0.113657,0.876883,0.508543,0.890652,-0.363184,0.555448,0.553633,...,0.210998,-2.275128,0.839030,1.423258,0.226041,-0.999037,-0.022102,0.995691,-0.962153,0.881340
C,1.524655,-0.499169,-0.086298,-1.178079,-0.246922,1.130949,-0.043144,-0.734456,0.570136,1.415721,...,0.357109,0.652479,0.190195,0.188119,0.321701,0.323290,0.366947,0.395024,-0.356978,-1.504520
D,-0.410939,-2.167667,-1.101403,-0.432215,-0.088183,1.622490,-0.167281,1.022984,0.259144,-0.231611,...,-1.004207,-0.316004,0.918515,-0.623009,0.397593,-0.538973,0.956740,-0.212480,-1.018043,-1.585582
E,-1.261822,0.709419,-0.094218,-0.913015,1.885315,-0.753579,-1.455542,0.018469,-0.140506,-0.346428,...,0.885807,-0.521750,-1.231180,0.108918,0.954388,-0.025525,1.232990,-0.719568,-1.264806,1.184420

In [17]:
df2 = pd.DataFrame({"A":7,
                  "B": pd.Timestamp('20190101'),
                  "C": pd.Series(1, index=list(range(4)), dtype='float32'),
                  "D": np.array([3] * 4, dtype='int32' ),
                  "E": pd.Categorical(["test","train","test","train"]),
                  "F": "Python" })

In [19]:
df2.T

,0,1,2,3
A,7,7,7,7
B,2019-01-01 00:00:00,2019-01-01 00:00:00,2019-01-01 00:00:00,2019-01-01 00:00:00
C,1.0,1.0,1.0,1.0
D,3,3,3,3
E,test,train,test,train
F,Python,Python,Python,Python

#Cast dos Dados para Numpy

In [21]:
df2.to_numpy()

array([[7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'test', 'Python'],
       [7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'train', 'Python'],
       [7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'test', 'Python'],
       [7, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'train', 'Python']],
      dtype=object)